#!/bin/bash
# Joins two json files on a shared field
# Usage:
# 	jqjoin a_and_b.json a_and_c.json id > a_and_b_and_c.json

fileA=$1
fileB=$2
field=$3

jq --arg field $field -n --slurpfile a1 $fileA --slurpfile a2 $fileB '(reduce $a1[] as $o ({};  . + { ($o | .[$field]): $o } )) as $h1 | (reduce $a2[] as $o ({};  . + { ($o | .[$field]): $o } )) as $h2 | reduce ($h1|keys[]) as $key ([]; if $h2|has($key) then . + [ $h1[$key] + $h2[$key] ] else . end)'
